### ISSUE TITLE
Encyclopedia: description field not visible without inserted text

### ISSUE THREAD

**Issue by hunzel** [Wavesonics/hammer-editor#10]
Hi!

I started a project in the current android app (1.0.7) and added a Encyclopida entry (person). I did not fill out the description field, but I wanted to do this later. I wanted to create all the persons, before going into depth and describing them. When reopening the person entry I was not able to find and edit the field for the description. I had to make a new entry with the description field filled out to see where I have to click. 
It would be great if there was an inline text of the empty field saying something like 'no description yet'.
Thank you!
Kind regards!

**Comment by Wavesonics** [comment]
Fixed! Will be in the next release
