### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by hunzel** [Wavesonics/hammer-editor#11]
Hi!

I wanted to ask if you would have a possibility to include different languages into the app/software?
Would be happy to contribute in translating to german, I am a native speaker.

Kind regards!

**Comment by Wavesonics** [comment]
Hey I think you are actually the very first user of the project other than my self!

I am definitely planning on localizing to other languages, I have already done the ground work for it. I just need to get the strings into files and setup with some sort of crowd sourced localization service. I will update this ticket when I've done so.

I've love any other feedback you have while using it, I have a discord setup for more informal feedback:
https://discord.gg/GTmgjZcupk

One thing I'd note about using the software is that it is very far from complete so far. I consider this to be very much Alpha quality software at the moment, and am not expecting to reach something like Beta quality until closer to the end of the year.

So user-beware at the moment!

**Comment by Wavesonics** [comment]
I got the project setup for localization here: https://hosted.weblate.org/projects/hammer/

Anyone can contribute strings as the project goes along now.

There is still a lot of work to do to get the project fully localizable, but I'll be doing it as I go.

**Comment by Wavesonics** [comment]
The Server & API have finally been put into the translation system, along with the missing client strings. At this point every user facing string that I'm aware of is in the translation system, and Weblate is setup to get them translated, so I'm going to consider this closed. Thanks for bringing it up! I hadn't considered translation at all before you did!
