### ISSUE TITLE
Crash when you use "[]" in notes section

### ISSUE THREAD

**Issue by wizhel** [Wavesonics/hammer-editor#152]
After making a note with a text like [Text], the app crashed whenever i try tap note section

**Comment by wizhel** [comment]
And i think the export feature is not working

**Comment by wizhel** [comment]
Im on Android 11 btw

**Comment by Wavesonics** [comment]
Ah yup, I see the problem, I'll get it fixed, thanks for the report!

**Comment by Wavesonics** [comment]
Fix for this will be included in the next release.
