### ISSUE TITLE
create note: pop up distorts when note is too long

### ISSUE THREAD

**Issue by hunzel** [Wavesonics/hammer-editor#17]
![Screenshot_20230612_023026_Hammer](https://github.com/Wavesonics/hammer-editor/assets/6576045/7bb909c7-2237-4164-a781-70c7e1858f1b)

In the create a note popup the overlaying window is getting distorted and the buttons for cancel and create will be completely gone when having a note that is more than three lines long. Also, the line break comes too late and the window grows more to the right, pushing text to left side.

**Comment by Wavesonics** [comment]
Fixed in 1.0.9
