### ISSUE TITLE
Some name problem in Chinese.

### ISSUE THREAD

**Issue by wzk0** [Wavesonics/hammer-editor#19]
I just wanna say that it's **the best and the most beautiful story editor** I have ever used. So I have already translated it in Simplified Chinese totally [here](https://hosted.weblate.org/languages/zh_Hans/hammer/), but there is still a problem when I try to create a new book.

Just as this photo shows, I am going to create a new book called "我". This is a Chinese character. But after tapping the `Create Project`, nothing happens. There is no new book called "我".

![Screenshot_2023-06-14-09-31-19-457_com darkrockstudios apps hammer android](https://github.com/Wavesonics/hammer-editor/assets/89891126/c286e61c-f82c-4394-85a0-60ffee62c06e)

The same problem is also found in `Creating Group` and `Creating Scene`.

I think what causes this problem may be the utf-8 code error (**Just guess! I know nothing about coding🤣**). I really love this software and hope you can fix this!

**Comment by Wavesonics** [comment]
This should be fixed now

**Comment by wzk0** [comment]
> This should be fixed now

Yeah! Thank U🥰

**Comment by Wavesonics** [comment]
Glad you're enjoying it! Could you check and see what version of the app you are using? It should be at the bottom of the App Drawer.

**Comment by Wavesonics** [comment]
Also, thank you for your translation work!

**Comment by wzk0** [comment]
> Glad you're enjoying it! Could you check and see what version of the app you are using? It should be at the bottom of the App Drawer.

The F-Droid shows that I am using the 1.0.8 version.

**Comment by Wavesonics** [comment]
okay, ya thats the latest, I'll take a look.

**Comment by wzk0** [comment]
> Also, thank you for your translation work!

It's my honor to work for such a good program! 😘

**Comment by Wavesonics** [comment]
If you're interested, theres a few other users on our Discord [here](https://discord.gg/GTmgjZcupk), so far mainly coordinating about translation, but also reporting bugs and discussing the app: https://discord.gg/GTmgjZcupk

**Comment by wzk0** [comment]
> 

OK! Love it.

**Comment by Wavesonics** [comment]
@wzk0 Could you retest in 1.1.0 and see if it still repros?

**Comment by wzk0** [comment]
> @wzk0 Could you retest in 1.1.0 and see if it still repros?

There is no problem in Chinese name, but some strings I used to translate are lost. 🤣

**Comment by Wavesonics** [comment]
Great! Ya I moved some strings around, a few might have gotten lost, sorry about that.

**Comment by wzk0** [comment]
> 

And I have done it right now! Loving Hammer!
