### ISSUE TITLE
App crashes after creating a scene (Android)

### ISSUE THREAD

**Issue by DragonWoven** [Wavesonics/hammer-editor#23]
When ever I create a scene or add a folder and then close the app and reload the project the app crashes.

**Comment by Wavesonics** [comment]
**If you could provide a little info:**
- What platform? Android?
- What version of the app (_you can find this at the bottom of the navigation draw_)
- What language?

**Comment by Wavesonics** [comment]
Ah yup, I found it, I'll get a fix out. Thanks for the report!

**Comment by Wavesonics** [comment]
This should be fixed in 1.1.0
