### ISSUE TITLE
Bug : can't delete folder or orphan scenes

### ISSUE THREAD

**Issue by lucastucious** [Wavesonics/hammer-editor#232]
In the chapter view, I can't delete folders or scene that don't have a folder (not even visible)

**Comment by Wavesonics** [comment]
I just tried some deletes and it seems to be working for me, could you provide a bit more info?

What client are you one, exactly what sort of scenes and groups do you have?

**Comment by lucastucious** [comment]
i'm on android, and long-pressing folder does nothing. 
For orphan scenes, it's scene that don't belong to a folder, and it's simply nowhere

**Comment by lucastucious** [comment]
![Screenshot_2024-01-31-08-57-52-98_f382130c23ef5b808f8b0388779c83ee.jpg](https://github.com/Wavesonics/hammer-editor/assets/28046122/39999cad-840b-440d-aabf-03a52e4303cb)

![Screenshot_2024-01-31-08-58-01-89_f382130c23ef5b808f8b0388779c83ee.jpg](https://github.com/Wavesonics/hammer-editor/assets/28046122/919271be-befe-4fe7-8a6f-9f37f216e255)

Here it says that I have 3 scenes, but I only have one. 

And the folder "tes" is un-deletable

**Comment by Wavesonics** [comment]
Ha, so the first problem, not being able to delete a scene, is a UX problem. 

On Android you need to swipe the row to the right to access it's menu. Which even I forgot, so maybe that's a problem.

The scene count there is counting the groups. I can get that fixed.

**Comment by Wavesonics** [comment]
Fixed the scene count, and will work on a better way to let users know they can swipe on the scene list
