### ISSUE TITLE
make different icons to understand that there are different functions.

### ISSUE THREAD

**Issue by Wjxfi** [Wavesonics/hammer-editor#24]
![86021b86-c919-4215-8011-5d3023b348ef.jpg](https://github.com/Wavesonics/hammer-editor/assets/113500363/cd245cb7-d880-48a0-aba8-5dd5182c1a7c)

![3713203d-3a84-4a3f-a5a7-f3dfabf45a8d.jpg](https://github.com/Wavesonics/hammer-editor/assets/113500363/10b87ce7-33a6-45ff-9671-7ee6fbd316e6)

**Comment by Wjxfi** [comment]
———
———  icon
———

**Comment by Wavesonics** [comment]
Sorry, not sure I understand what you mean. Where exactly do you want icons?

**Comment by Wjxfi** [comment]
When you click the button on the top left in different tabs, different functions open with the same icon. Change the icon on the top left to a different icon on the tab when you click on a project. it is necessary to understand that there are different functions in this button

**Comment by Wavesonics** [comment]
This was released in 1.6.0
