### ISSUE TITLE
Is there an Hammer edition for Raspberry Pi OS?

### ISSUE THREAD

**Issue by serrq** [Wavesonics/hammer-editor#248]
And any other Linux desktop distribution... (FreeBSD, Debian, etc.).

**Comment by Wavesonics** [comment]
We're already producing `.deb` files which might help you, take a look at the binaries on a release:
https://github.com/Wavesonics/hammer-editor/releases/tag/v1.7.0

I plan on producing snap and flatpaks in the future, but I just don't know how to do it yet, and its not very high on the priority list at the moment.

If anyone knows how to package for those other formats and wants to contribute it would be greatly appreciated!

**Comment by serrq** [comment]
Unfortunately I am not a developer, just a normal user.
