### ISSUE TITLE
Server login dialog does not accept URL containing both subdomains and numbers before port component

### ISSUE THREAD

**Issue by blujai831** [Wavesonics/hammer-editor#27]
If a URL containing *both* at least one subdomain component, *and* numbers before the port component but after the leading subdomain component, is given during server login, the dialog reports "Invalid URL." Consider for example the URL `hammer.blujai831.dev`.

The cause of the problem seems to be in `common/src/commonMain/kotlin/com/darkrockstudios/apps/hammer/common/components/projectselection/accountsettings/AccountSettingsComponent.kt`, wherein `urlWithPortRegex` is defined as `Regex("""^(?:w{1,3}\.)?[^\s.]+(?:\.[a-z]+)*(?::\d+)?(?![^<]*(?:</\w+>|/?>))$""")`.

I suspect the specific cause of the issue is the use of `[a-z]+`, rather than, e.g., `[a-z0-9]+`, in the `(?:\.[a-z]+)*` part. Until I took a closer look at the regex, I assumed the problem was just _any_ URL with a subdomain, as I did not experience the issue until trying to use one, but on closer inspection, it looks like the regex should have no problem handling subdomains _if_ the root domain name does _not_ contain numbers.

On further consideration, I realize it might be difficult to fix this issue without creating overlap between this regex and the IP regex. If that's the case, I might recommend sidestepping the overlap by having the IP regex take precedence and using the URL regex as a fallback, and/or making the "Invalid URL" error advisory rather than restrictive.

**Comment by Wavesonics** [comment]
yup looks like that regex is far too restrictive, will work on a better on

**Comment by Wavesonics** [comment]
Resolved in commit: e6326bee67d8a4f1ef8d3a5c2befeea413a12788
