### ISSUE TITLE
widget shows demo category 

### ISSUE THREAD

**Issue by pantheonw** [Wavesonics/hammer-editor#32]
Android 11, hammer 1.1.0
I deleted the Alice in Wonderland Project but the widget shows both the actual project I have and Alice in Wonderland. Just checked and it is apparently in order of project created, the new project I created was added to the end of the list. It did also remove the new project from the list when I deleted it.

**Comment by Wavesonics** [comment]
Thanks for the report! Will look into it.

**Comment by Wavesonics** [comment]
Hhmmm I cannot reproduce this.

There's been some work on the widget since the version you tested on, so maybe retest once I release 1.4.0 which has a lot of widget changes in it.
