### ISSUE TITLE
App keeps crashing whenever I try to edit a chapter

### ISSUE THREAD

**Issue by SecularSteve** [Wavesonics/hammer-editor#38]
Every single time I open "Alice in Wonderland", and go to edit one of the chapters, the app crashes every single time. And I just downloaded it.

My device is an Android "Sony Xperia 1 II" in case it's important.

Then again, the Edit Page is unusually laggy. Like it's literally taking up too many resources all at once.

If you require more information, I'll be glad to share it.

**Comment by Wavesonics** [comment]
Yes, I just released a fix for this in version 1.2.1, please check your app store for an update, it might take a few hours from this message for it to propagate through.
