### ISSUE TITLE
Android keyboard hides the bottom section of the editor

### ISSUE THREAD

**Issue by Rokhala** [Wavesonics/hammer-editor#47]
When I try to write and bring up the keyboard, the text at the bottom of the screen is covered by the keyboard.
The screenshot here show a blue arrow pointing at the current typing position.

![Screenshot_20230826-123040_Hammer](https://github.com/Wavesonics/hammer-editor/assets/124471518/9456055d-2b3e-4082-9318-71e50900eeec)

**Comment by Wavesonics** [comment]
Thanks for the report! It's been fixed and will be included in the next release.
